const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const {Worker}=require('node:worker_threads');const {decodeWav,compare}=require('./audio-analysis.cjs');
/* 拒绝录音时要把"怎么改"一起说清楚：老师看到的不能只是一句"无效"。 */
const fail=(message,hint)=>Object.assign(new Error(message),{hint});
const WAV_HINT='只接受 1–20 秒、16kHz 单声道、16 位 PCM 的录音：请在页面上直接录音，或上传浏览器可解码的音频（上传时会自动混合为单声道）。';
function createAudioStore(dataDir,opts={}){const {loadLesson,retentionDays:retentionOpt}=opts;/* 录音保留期（天）：到期只删 WAV 音频本身，测量与诊断记录保留并标记 audioDeleted。
   0 表示关闭自动删除；未显式配置时读环境变量 AUDIO_RETENTION_DAYS，再未配置则默认 30 天 —— 宁可少留，不留隐患。 */
const retentionDays=(()=>{const raw=retentionOpt!==undefined?retentionOpt:process.env.AUDIO_RETENTION_DAYS;if(raw===undefined||raw===null||raw==='')return 30;const n=Math.floor(Number(raw));return Number.isFinite(n)&&n>=0?n:30})();const dir=path.join(dataDir,'audio-attempts');fs.mkdirSync(dir,{recursive:true});const busy=new Set();const save=r=>{const f=path.join(dir,r.id+'.json');fs.writeFileSync(f+'.tmp',JSON.stringify(r,null,2),{mode:0o600});fs.renameSync(f+'.tmp',f)};
const get=(id,owner)=>{if(!/^[a-f0-9-]{36}$/.test(id))return null;const file=path.join(dir,id+'.json');if(!fs.existsSync(file))return null;const r=JSON.parse(fs.readFileSync(file,'utf8'));return r.owner===owner?r:null};
/* 保留期清扫：删除到期的 WAV 音频文件，记录本身保留（测量、诊断、比较结果不受影响）。
   这是有意的取舍——课堂报告要继续可用，但原始声音不该在服务器上无限期留存。 */
const sweepExpired=(now=Date.now())=>{if(!retentionDays)return{enabled:false,checked:0,removed:0};const cutoff=new Date(now-retentionDays*86400000).toISOString();let checked=0,removed=0;for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.json'))){const file=path.join(dir,f);let r;try{r=JSON.parse(fs.readFileSync(file,'utf8'))}catch{continue}checked++;if(r.audioDeleted||!(String(r.createdAt||'')<cutoff))continue;try{fs.rmSync(path.join(dir,r.id+'.wav'),{force:true})}catch{}r.audioDeleted=true;r.audioDeletedAt=new Date(now).toISOString();save(r);removed++}return{enabled:true,retentionDays,checked,removed,cutoff}};
return {get,retentionDays,sweepExpired,list(owner){return fs.readdirSync(dir).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'))).filter(r=>r.owner===owner).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,30)},audio(id,owner){const r=get(id,owner);if(!r||r.audioDeleted)return null;return fs.readFileSync(path.join(dir,id+'.wav'))},practice(id,owner){const r=get(id,owner);if(!r)throw Error('录音不存在');r.practiceRequests.push({time:new Date().toISOString(),action:r.analysis.decision.action,status:'requested'});save(r);return r},async submit(owner,input){if(busy.has(owner)||busy.size>=2)throw Error('音频分析中，请稍后重试');if(typeof input.audio!=='string'||input.audio.length>860000||!/^[A-Za-z0-9+/]*={0,2}$/.test(input.audio))throw fail('音频数据无效或超过20秒',WAV_HINT);if(!['single','group'].includes(input.context))throw Error('请声明单人或多人录音');const wav=Buffer.from(input.audio,'base64');let samples;try{samples=decodeWav(wav)}catch(e){throw fail(e.message,WAV_HINT)}const sha256=crypto.createHash('sha256').update(wav).digest('hex');const previous=input.previousId?get(input.previousId,owner):null;if(input.previousId&&!previous)throw Error('首次录音不存在或无权访问');if(previous&&previous.sha256===sha256)throw Error('复测必须使用第二份录音，不能重复提交同一音频');busy.add(owner);try{const analysis=await new Promise((resolve,reject)=>{const lesson=typeof loadLesson==='function'?loadLesson(input.lessonId):undefined;const worker=new Worker(path.join(__dirname,'audio-worker.cjs'),{workerData:{samples,context:input.context,lesson}}),timer=setTimeout(()=>{void worker.terminate();reject(Error('分析超时，请缩短录音后重试'))},15000);worker.once('message',r=>{clearTimeout(timer);r.error?reject(Error(r.error)):resolve(r)});worker.once('error',()=>{clearTimeout(timer);reject(Error('音频分析失败，请重试'))});worker.once('exit',code=>{clearTimeout(timer);if(code!==0)reject(Error('音频分析中断'))})});const r={id:crypto.randomUUID(),owner,createdAt:new Date().toISOString(),sha256,format:'PCM16 mono 16000Hz',context:input.context,source:input.source==='microphone'?'microphone':'uploaded-audio',previousId:previous?.id||null,comparison:previous?compare(previous.analysis,analysis):null,analysis,practiceRequests:[],...(retentionDays?{retentionDays,expiresAt:new Date(Date.now()+retentionDays*86400000).toISOString()}:{})};fs.writeFileSync(path.join(dir,r.id+'.wav'),wav,{mode:0o600});save(r);return r}finally{busy.delete(owner)}}};}
module.exports={createAudioStore};
