const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),lesson=require('../public/lessons/molihua.lesson.json'),core=require('../public/lesson-core.js');core.validate(lesson);
const {renderWav}=require('../server/audio-render.cjs'); // 合成逻辑只有一份，导入的乐谱也走这里
const out=path.join(root,'public/assets/audio');fs.mkdirSync(out,{recursive:true});
const files=[['molihua-c-80.wav',80,0],['molihua-c-60.wav',60,0],['molihua-c-80-countin.wav',80,4]],manifest={lessonId:lesson.id,version:lesson.version,sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'public/lessons/molihua.lesson.json'))).digest('hex'),files:[]};
for(const [file,bpm,countIn] of files){const data=renderWav(lesson,bpm,countIn);fs.writeFileSync(path.join(out,file),data);manifest.files.push({file,bpm,countIn,durationSeconds:(data.length-44)/2/lesson.audio.sampleRate,sha256:crypto.createHash('sha256').update(data).digest('hex')})}
fs.writeFileSync(path.join(root,'public/lessons/molihua.data.js'),'/* Generated by build-lesson.cjs; edit the JSON source. */\nwindow.MOLIHUA_LESSON='+JSON.stringify(lesson)+';\n');
fs.writeFileSync(path.join(root,'public/lessons/audio-manifest.json'),JSON.stringify(manifest,null,2));
const samplePlan=core.buildPlan(lesson,{duration:40,students:28,grade:'四年级',level:'初学者',equipment:'无钢琴'});fs.writeFileSync(path.join(root,'public/lessons/molihua-plan-example.json'),JSON.stringify(samplePlan,null,2));console.log(JSON.stringify(manifest,null,2));
