const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'..');
// 用法：node scripts/build-lesson.cjs [lesson文件路径，默认 molihua.lesson.json]
// 由课程 JSON 生成：参考/慢速/含预备拍 WAV + 带歌词示范 WAV + 浏览器数据文件 + 音频清单。
const lessonPath=path.resolve(root,process.argv[2]||'public/lessons/molihua.lesson.json');
const lesson=require(lessonPath),core=require('../public/lesson-core.js');core.validate(lesson);
const {renderWav,renderVocalWav}=require('../server/audio-render.cjs'); // 合成逻辑只有一份，导入的乐谱也走这里
const out=path.join(root,'public/assets/audio');fs.mkdirSync(out,{recursive:true});
// 文件前缀从 audio.reference 反推（"assets/audio/molihua-c-80.wav" → "molihua"），
// 保证生成的文件名与 lesson.json 里 audio 各字段的路径严格一致，不受 id 命名影响。
const refName=path.basename(lesson.audio.reference);
const stem=refName.replace(/-c-\d+\.wav$/,'');
const files=[[`${stem}-c-${lesson.teaching.bpm}.wav`,lesson.teaching.bpm,0],[`${stem}-c-${lesson.teaching.slowBpm}.wav`,lesson.teaching.slowBpm,0],[`${stem}-c-${lesson.teaching.bpm}-countin.wav`,lesson.teaching.bpm,4],[`${stem}-c-${lesson.teaching.bpm}-vocal.wav`,lesson.teaching.bpm,0,'vocal'],[`${stem}-c-${lesson.teaching.slowBpm}-vocal.wav`,lesson.teaching.slowBpm,0,'vocal']],manifest={lessonId:lesson.id,version:lesson.version,sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(lessonPath)).digest('hex'),files:[]};
for(const [file,bpm,countIn,vocal] of files){const data=vocal?renderVocalWav(lesson,bpm,countIn):renderWav(lesson,bpm,countIn);fs.writeFileSync(path.join(out,file),data);manifest.files.push({file,bpm,countIn,vocal:Boolean(vocal),durationSeconds:(data.length-44)/2/lesson.audio.sampleRate,sha256:crypto.createHash('sha256').update(data).digest('hex')})}
// 浏览器数据文件：全局变量名与文件名都从 stem 生成（molihua → MOLIHUA_LESSON / molihua.data.js）
const globalName=stem.replace(/-/g,'_').toUpperCase()+'_LESSON';
const dataFile=path.join(root,'public/lessons',stem+'.data.js');
fs.writeFileSync(dataFile,'/* Generated by build-lesson.cjs; edit the JSON source. */\nwindow.'+globalName+'='+JSON.stringify(lesson)+';\n');
// 音频清单只在默认课程（茉莉花）时覆盖，避免多课程互相覆盖
if(process.argv[2]===undefined)fs.writeFileSync(path.join(root,'public/lessons/audio-manifest.json'),JSON.stringify(manifest,null,2));
console.log(JSON.stringify({lessonId:lesson.id,globalName,dataFile:path.basename(dataFile),files:manifest.files.map(f=>f.file)},null,2));
